<a href="https://colab.research.google.com/github/katya123123/ML-labs/blob/main/ML_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import matplotlib.pyplot as plt
import pandas as pd
import math

In [48]:
df = pd.read_csv("/content/student-mat.csv")

In [49]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [50]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

## Обработка пропусков

In [51]:
df['Mjob'][350:] = None
df['absences'][:150] = None
df

<ipython-input-51-906ecece7291>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mjob'][350:] = None
<ipython-input-51-906ecece7291>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['absences'][:150] = None

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,NaN,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,NaN,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,NaN,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,NaN,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,NaN,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,None,services,...,5,5,4,4,5,4,11.0,9,9,9
391,MS,M,17,U,LE3,T,3,1,None,services,...,2,4,5,3,4,2,3.0,14,16,16
392,MS,M,21,R,GT3,T,1,1,None,other,...,5,5,3,3,3,3,3.0,10,8,7
393,MS,M,18,R,LE3,T,3,2,None,other,...,4,4,1,3,4,5,0.0,11,12,10
394,MS,M,19,U,LE3,T,1,1,None,at_home,...,3,2,3,3,3,5,5.0,8,9,9

In [52]:
df_cleaned = df.copy()
df_cleaned = df.dropna()
df_cleaned

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
150,GP,M,18,U,LE3,T,1,1,other,other,...,2,3,5,2,5,4,0.0,6,5,0
151,GP,M,16,U,LE3,T,2,1,at_home,other,...,4,4,4,3,5,5,6.0,12,13,14
152,GP,F,15,R,GT3,T,3,3,services,services,...,4,2,1,2,3,3,8.0,10,10,10
153,GP,M,19,U,GT3,T,3,2,services,at_home,...,4,5,4,1,1,4,0.0,5,0,0
154,GP,F,17,U,GT3,T,4,4,other,teacher,...,4,2,1,1,1,4,0.0,11,11,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,GP,F,18,U,GT3,T,3,2,other,services,...,5,4,3,2,3,1,7.0,13,13,14
346,GP,M,18,R,GT3,T,4,3,teacher,services,...,5,3,2,1,2,4,9.0,16,15,16
347,GP,M,18,U,GT3,T,4,3,teacher,other,...,5,4,5,2,3,5,0.0,10,10,9
348,GP,F,17,U,GT3,T,4,3,health,other,...,4,4,3,1,3,4,0.0,13,15,15
349,MS,M,18,R,GT3,T,3,2,other,other,...,2,5,5,5,5,5,10.0,11,13,13

In [53]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,245.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,6.387755,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.729581,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,9.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

Среднее значение показателя пропусков довольно значительно изменилось по сравнению с изначальными значениями, поскольку мы "потеряли" часть значений. Изменилось, хоть и не так значительно, среднеквадратичное отклонение, оно стало больше, что означает, что значения стали более "разбросаны" в своём интервале.

In [54]:
df_filled_by_mean = df.copy()
df_filled_by_mean['absences'] = df['absences'].fillna(df['absences'].mean())
df_filled_by_mean

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6.387755,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,6.387755,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6.387755,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,6.387755,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,6.387755,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,None,services,...,5,5,4,4,5,4,11.000000,9,9,9
391,MS,M,17,U,LE3,T,3,1,None,services,...,2,4,5,3,4,2,3.000000,14,16,16
392,MS,M,21,R,GT3,T,1,1,None,other,...,5,5,3,3,3,3,3.000000,10,8,7
393,MS,M,18,R,LE3,T,3,2,None,other,...,4,4,1,3,4,5,0.000000,11,12,10
394,MS,M,19,U,LE3,T,1,1,None,at_home,...,3,2,3,3,3,5,5.000000,8,9,9

In [55]:
df_filled_by_mean.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,6.387755,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,6.869739,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,2.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,6.387755,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.387755,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

Заполнение пропуска средним значением также привел к значительному изменению среднего, однако в данном случае очень сильно уменьшилось среднеквадратичное отклонение. Так произошло по причине того, что огромная часть значений теперь являются средним значением, соответствие и разброс значений стал куда меньше относительно среднего. При этом стоит отметить, что значительно измениля 2 и 3 квартили. На мой взгляд, такие данные уже не подходят для анализа.

In [56]:
df_filled_by_median = df.copy()
df_filled_by_median['absences'] = df['absences'].fillna(df['absences'].median())
df_filled_by_median

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4.0,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4.0,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,4.0,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,4.0,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4.0,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,None,services,...,5,5,4,4,5,4,11.0,9,9,9
391,MS,M,17,U,LE3,T,3,1,None,services,...,2,4,5,3,4,2,3.0,14,16,16
392,MS,M,21,R,GT3,T,1,1,None,other,...,5,5,3,3,3,3,3.0,10,8,7
393,MS,M,18,R,LE3,T,3,2,None,other,...,4,4,1,3,4,5,0.0,11,12,10
394,MS,M,19,U,LE3,T,1,1,None,at_home,...,3,2,3,3,3,5,5.0,8,9,9

In [57]:
df_filled_by_median.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.481013,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,6.967038,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,2.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,5.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

При заполнении пропуском медианой мы видим, что изменение среднего незначительно и при этом среднеквадратичное отклонение значительно уменьшилось. Данные при таком способе заполнения пропуска притерпели минимальные изменения.

In [58]:
print(df['absences'].mean(), df['absences'].median())

6.387755102040816 4.0

Заполнение значений необходимо, чтобы не терять строки с нулл-значениями, что происходит при обычном удалении нулл-значений. Самыми простыми способами заполнения значений являются заполнение на основе среднего и медианы.

В данном случае, медиана значительно отличается от среднего, за счет чего оба способа дают различный рельтат. Первый способ скорее подошел бы, если бы эта колонка не влияла на результат итоговых вычислений и анализа данных, а второй способ подойдет, если значение колонки влияет на конечный результат и нам важно сохранить корректность данных, но при этом заполнить пропуски.

In [59]:
df_filled_by_moda  = df.copy()
df_filled_by_moda['Mjob'] = df['Mjob'].fillna(df['Mjob'].mode()[0])
df_filled_by_moda

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,NaN,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,NaN,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,NaN,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,NaN,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,NaN,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,other,services,...,5,5,4,4,5,4,11.0,9,9,9
391,MS,M,17,U,LE3,T,3,1,other,services,...,2,4,5,3,4,2,3.0,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3.0,10,8,7
393,MS,M,18,R,LE3,T,3,2,other,other,...,4,4,1,3,4,5,0.0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5.0,8,9,9

Так как пропуски встречаются в том числе и в колонке Mjob, которая является категориальной, её пустые значения необходимо заполнить на основе моды. Значения заполнились значением other, поскольку это самое часто встречающееся слово в данной колонке.

In [60]:
df_interpolated = df.copy()
for i in range(len(df_interpolated['absences'])):
  if df_interpolated['absences'][i] == None:
    continue
  else:
    df_interpolated['absences'][i] = df_interpolated['absences'][i].astype('int')
df_interpolated['absences'] = df_interpolated['absences'].interpolate()
df_interpolated

<ipython-input-60-d738d5d09255>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_interpolated['absences'][i] = df_interpolated['absences'][i].astype('int')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,-9.223372e+18,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,-9.223372e+18,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,-9.223372e+18,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,-9.223372e+18,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,-9.223372e+18,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,None,services,...,5,5,4,4,5,4,1.100000e+01,9,9,9
391,MS,M,17,U,LE3,T,3,1,None,services,...,2,4,5,3,4,2,3.000000e+00,14,16,16
392,MS,M,21,R,GT3,T,1,1,None,other,...,5,5,3,3,3,3,3.000000e+00,10,8,7
393,MS,M,18,R,LE3,T,3,2,None,other,...,4,4,1,3,4,5,0.000000e+00,11,12,10
394,MS,M,19,U,LE3,T,1,1,None,at_home,...,3,2,3,3,3,5,5.000000e+00,8,9,9

In [61]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,245.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,6.387755,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.729581,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,9.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

Данный метод работет крайне криво за счет того, что у нас много подряд пустых значений, а они не разбросаны как единичные случаи по колонке. Таким образом, данный способ подходит только в том случае, когда нет множества подряд пропущенных значений.

## Выбросы и аномалии

In [62]:
class Outline:
  def __init__(self, df):
    self.df = df

  def del_outline_by_mean(self, col):
    arr =[]
    mean = df[col].mean()
    std = df[col].std()
    median = df[col].median()
    N = df[col].count()
    if median - mean <= 3 * math.sqrt(std**2/N):
      cof = 3
    else:
      cof = 5
    min = mean - cof * std
    max = mean + cof * std
    for ind, v in self.df[col].items():
      if (v <= min) or (v >= max):
        arr.append(ind)

    return print("Индексы выбросов по среднему", arr)

  def del_outline_by_shovene(self, col):
    df = self.df[col].copy()
    arrSh = []
    n = df.count()
    for  ind, v in df.items():
      meanSh = df.mean()
      stdSh = df.std()
      if math.erfc((abs(v-meanSh))/stdSh) < 1/(2*n):
        arrSh.append(ind)
      else:
        n -= 1
        df = df.drop(index = ind)

    return print("Индексы выбросов по Шовене: ", arrSh)

  def del_outline_by_qu(self, col):
    arrQ = []
    Q1 = self.df[col].quantile(0.25)
    Q2 = self.df[col].quantile(0.5)
    Q3 = self.df[col].quantile(0.75)
    min = Q1-1.5*(Q3-Q1)
    max = Q3+1.5*(Q3-Q1)
    for ind, v in self.df[col].items():
      if (v <= min) or (v >= max):
        arrQ.append(ind)
    return print("Индексы выбросов по квартилям: ", arrQ)

  def del_outline_by_DBSCAN(self, col1, col2):
    new_df = self.df[[col1, col2]]
    temp_df = self.df[[col1, col2]]
    cluster = DBSCAN(eps = 2, min_samples = 1).fit(new_df)
    new_df['labels']  = cluster.labels_
    temp_df['labels']  = cluster.labels_
    labels= list(new_df['labels'])
    uniq, count = np.unique(labels, return_counts=True)
    dict_of_uniq= dict(zip(uniq, count))
    outline_cluster = []
    for k,v in dict_of_uniq.items():
      if v <=2:
        outline_cluster.append(k)
    temp_df = new_df[new_df['labels'].isin(outline_cluster)].index
    new_df = new_df[~new_df['labels'].isin(outline_cluster)]
    fig = plt.scatter(new_df, x = col1, y = col2, color = 'labels')
    fig.show()
    print(temp_df)

In [63]:
df_outlinered_by_mean = df.copy()
ind_of_outline = Outline(df_outlinered_by_mean)
ind_of_outline.del_outline_by_mean("absences")

Индексы выбросов по среднему [183, 276, 307, 315]

In [64]:
df_outlinered_by_q = df.copy()
ind_of_outline_by_q = Outline(df_outlinered_by_q)
ind_of_outline_by_q.del_outline_by_qu("absences")

Индексы выбросов по квартилям:  [183, 198, 205, 276, 280, 307, 315, 320]

# Дубликаты

In [67]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,245.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,6.387755,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.729581,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,9.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [78]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

Вывод: в данном сете нет дубликатов

In [72]:
df_concated = df.copy()
df_concated = pd.concat((df, df.loc[100:]))

In [70]:
df_concated.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,490.000000,690.000000,690.000000,690.000000
mean,16.865217,2.701449,2.508696,1.466667,2.026087,0.352174,3.939130,3.236232,3.13913,1.491304,2.320290,3.544928,6.387755,10.923188,10.617391,10.259420
std,1.256891,1.096570,1.091229,0.708371,0.834254,0.755648,0.893001,1.002532,1.11764,0.895439,1.293175,1.373134,8.720651,3.324040,3.804548,4.697614
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.00000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.00000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.00000,2.000000,3.000000,5.000000,9.000000,13.000000,13.000000,13.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [73]:
df_no_dupl = df.drop_duplicates()
df_no_dupl.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,245.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,6.387755,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.729581,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,9.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

# Преобразование признаков